### ISSUE TITLE
In moodle-plugin-ci.yml, check MOODLE_402_STABLE and MOODLE_403_STABLE as well as PHP 8.2 should be tested

### ISSUE THREAD

**Issue by lucaboesch** [bschur/moodle-qtype_uml#1]
In .github/workflows/moodle-plugin-ci.yml you could support MOODLE_402_STABLE and MOODLE_403_STABLE as well. And PHP 8.2. Therefore, the lines 32, 33 and 34 should be extended. Make sure you lift mariadb in line 20 to 10.6 (since that's the minimum version for Moodle 4.3).
Since Moodle 4.3 and Moodle 4.2 do not support PHP 7.4 any more, the matrix for the tests has to be written differently. I normally go for something like verbatim listing the branches and php versions

```
      matrix:
        include:
          - php: 8.2
            moodle-branch: MOODLE_403_STABLE
            database: pgsql
          - php: 8.2
            moodle-branch: MOODLE_403_STABLE
            database: mariadb
          - php: 8.2
            moodle-branch: MOODLE_402_STABLE
            database: pgsql
          - php: 8.2
            moodle-branch: MOODLE_402_STABLE
            database: mariadb

          - php: 8.1
            moodle-branch: MOODLE_403_STABLE
            database: pgsql
          - php: 8.1
            moodle-branch: MOODLE_403_STABLE
            database: mariadb
          - php: 8.1
            moodle-branch: MOODLE_402_STABLE
            database: pgsql
          - php: 8.1
            moodle-branch: MOODLE_402_STABLE
            database: mariadb
          - php: 8.1
            moodle-branch: MOODLE_401_STABLE
            database: pgsql
          - php: 8.1
            moodle-branch: MOODLE_401_STABLE
            database: mariadb

          - php: 8.0
            moodle-branch: MOODLE_403_STABLE
            database: pgsql
          - php: 8.0
            moodle-branch: MOODLE_403_STABLE
            database: mariadb
          - php: 8.0
            moodle-branch: MOODLE_402_STABLE
            database: pgsql
          - php: 8.0
            moodle-branch: MOODLE_402_STABLE
            database: mariadb
          - php: 8.0
            moodle-branch: MOODLE_401_STABLE
            database: pgsql
          - php: 8.0
            moodle-branch: MOODLE_401_STABLE
            database: mariadb

          - php: 7.4
            moodle-branch: MOODLE_401_STABLE
            database: pgsql
          - php: 7.4
            moodle-branch: MOODLE_401_STABLE
            database: mariadb

```
